# -*- coding: utf-8 -*-
"""Data Processing and Visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HKr1HE6dMb78bO82I9_QEMlaYhi8sw7f
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Set the style for the plots
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)

def load_data(filepath):
    """Loads the dataset."""
    try:
        df = pd.read_csv(filepath)
        print("Data loaded successfully.")
        return df
    except FileNotFoundError:
        print(f"Error: File '{filepath}' not found. Please ensure the dataset is in the same directory.")
        return None

def clean_data(df):
    """
    Performs data cleaning and transformation steps.
    """
    print("\n--- Starting Data Cleaning ---")

    # 1. Handling Missing Values
    # 'director', 'cast', and 'country' have nulls. We fill them with 'Unknown' or mode.
    df['director'] = df['director'].fillna('Unknown Director')
    df['cast'] = df['cast'].fillna('Unknown Cast')
    df['country'] = df['country'].fillna(df['country'].mode()[0])

    # Drop rows where 'date_added' or 'rating' is missing (small percentage usually)
    df.dropna(subset=['date_added', 'rating'], inplace=True)

    # 2. Date Transformation
    # Convert 'date_added' to datetime objects
    df['date_added'] = pd.to_datetime(df['date_added'].str.strip(), format='mixed', errors='coerce')

    # Extract Year and Month added
    df['year_added'] = df['date_added'].dt.year
    df['month_added'] = df['date_added'].dt.month_name()

    # 3. Release Year Validation
    # Ensure release_year is valid (optional check)

    print("Data cleaning completed.")
    print(f"Remaining Missing Values:\n{df.isnull().sum()}")
    return df

def generate_visualizations(df):
    """
    Generates visualizations for the analysis report.
    """
    print("\n--- Generating Visualizations ---")

    # 1. Content Distribution: Movie vs TV Show
    plt.figure(figsize=(8, 8))
    df['type'].value_counts().plot.pie(autopct='%1.1f%%', startangle=90, colors=['#e50914', '#221f1f'], explode=[0.05, 0])
    plt.title('Distribution of Netflix Content: Movies vs TV Shows')
    plt.ylabel('')
    plt.savefig('viz_content_distribution.png')
    plt.close()

    # 2. Content Added Over Time
    plt.figure(figsize=(12, 6))
    vc_year = df['year_added'].value_counts().sort_index()
    sns.lineplot(x=vc_year.index, y=vc_year.values, color='#e50914', marker='o')
    plt.title('Content Added to Netflix Over the Years')
    plt.xlabel('Year')
    plt.ylabel('Number of Titles')
    plt.savefig('viz_content_trend.png')
    plt.close()

    # 3. Top 10 Countries
    # Note: Some titles have multiple countries listed. We take the primary one for simplicity.
    plt.figure(figsize=(12, 6))
    primary_country = df['country'].apply(lambda x: x.split(',')[0])
    sns.countplot(y=primary_country, order=primary_country.value_counts().index[:10], palette='Reds_r')
    plt.title('Top 10 Countries Producing Netflix Content')
    plt.xlabel('Count')
    plt.ylabel('Country')
    plt.savefig('viz_top_countries.png')
    plt.close()

    # 4. Rating Distribution
    plt.figure(figsize=(14, 7))
    sns.countplot(x='rating', data=df, order=df['rating'].value_counts().index, palette='Spectral')
    plt.title('Distribution of Content Ratings')
    plt.xticks(rotation=45)
    plt.savefig('viz_ratings.png')
    plt.close()

    print("Visualizations saved as PNG files.")

def main():
    # Assume dataset is named 'netflix_titles.csv'
    df = load_data('netflix_titles.csv')

    if df is not None:
        df_clean = clean_data(df)

        # Save cleaned data for Power BI or SQL usage if needed
        df_clean.to_csv('netflix_cleaned.csv', index=False)
        print("Cleaned data saved to 'netflix_cleaned.csv'")

        generate_visualizations(df_clean)
        print("\nWorkflow completed successfully.")

if __name__ == "__main__":
    main()